var all = ["a new reign",
"abigail",
"abigail's flower",
"abyss",
"accomploshrine",
"advanced world",
"adventure",
"adventure mode",
"alchemy engine",
"all about night",
"all eggs",
"amulet",
"ancient",
"ancient altar",
"ancient civilization",
"ancient guardian",
"ancient pseudoscience station",
"ancient statue",
"ancient tab",
"animal",
"animals",
"anti venom",
"applied horticulture",
"armor",
"armored boat",
"armors",
"armour",
"armours",
"ash",
"ash tree",
"ashes",
"ashy turf",
"asleep",
"autumn",
"axe",
"azure feather",
"baby beefalo",
"baby tentacle",
"backpack",
"bacon and eggs",
"ball and cup",
"balloonomancy",
"balloons",
"ballphin free tuna",
"bamboo",
"bamboo patch",
"banana",
"banana pop",
"bandage",
"barrel",
"barrels",
"basalt",
"basalt pillar",
"basic farm",
"bat",
"bat bat",
"bat cave",
"batilisk",
"batilisk wing",
"batilisk wings",
"batilisks",
"battle helm",
"battle spear",
"beach",
"beard",
"beard hair",
"bearded",
"beardling",
"beardlings",
"beardlord",
"beardlords",
"bearger",
"bed roll",
"bee",
"bee box",
"bee hive",
"bee hives",
"bee mine",
"bee mines",
"bee queen",
"beefalo",
"beefalo hair",
"beefalo hat",
"beefalo heat",
"beefalo horn",
"beefalo wool",
"beefalos",
"beehive",
"beehives",
"beekeeper hat",
"bees",
"belt of hunger",
"bernie",
"berries",
"berry",
"berry bush",
"berry bush",
"berry bushes",
"big tentacle",
"bioluminescence",
"biome",
"biomes",
"birchnut",
"birchnutter",
"bird cage",
"bird trap",
"bird trap",
"bird traps",
"birdcage",
"birdcages",
"birds",
"birds of the world",
"bisque",
"blind box collectible",
"blow dart",
"blow darts",
"blubber",
"blubber suit",
"blue cap",
"blue funcap",
"blue gem",
"blue gems",
"blue hound",
"blue hounds",
"blue moonlens",
"blue mushroom",
"blue mushtree",
"blue mushtrees",
"blue spore",
"blue whale",
"blue whales",
"blueprint",
"blueprints",
"board",
"boards",
"boat",
"boat cannon",
"boat lantern",
"boat repair kit",
"boat torch",
"boats",
"bone key",
"bone shards",
"bones",
"bonfire",
"books",
"books tab",
"boomerang",
"boon",
"boons",
"booster shot",
"booty bag",
"boss",
"boss monster",
"boss monsters",
"bosses",
"bottle lantern",
"bottlenose ballphin",
"boulder",
"boulders",
"box thing",
"brain of thought",
"brainy matter",
"brainy sprout",
"braised eggplant",
"breezy vest",
"bridge",
"broken clockworks",
"broken shell",
"broken shells",
"broodling",
"brush",
"buffalo",
"bug net",
"bunny puff",
"bunny puffs",
"bunnyman",
"bunnymen",
"buoy",
"burning",
"burnt tree",
"burrow",
"bush hat",
"butter",
"butter muffin",
"butterflies",
"butterfly",
"butterfly wings",
"buzzard",
"cacti",
"cactus",
"cactus armor",
"cactus flesh",
"cactus flower",
"cactus spike",
"california roll",
"camp fire",
"campfire",
"campfires",
"camping underground",
"canary",
"candy bag",
"cane",
"captain hat",
"cargo boat",
"carpeted flooring",
"carrot",
"carrot house",
"carrot houses",
"carrot seeds",
"carrots",
"cartographer's desk",
"cartography",
"cartography tab",
"cat cap",
"cat coon",
"cat tail",
"catcoon",
"cave",
"cave banana tree",
"cave banana trees",
"cave bananas",
"cave entrance",
"cave lichen",
"cave rock turf",
"cave spider",
"cave spiders",
"caves",
"ceviche",
"character",
"character quotes",
"characters",
"charcoal",
"charlie",
"cheat codes",
"checkerboard flooring",
"chef pouch",
"chess",
"chess monsters",
"chess pieces",
"chest",
"chest of the depths",
"chester",
"chests",
"chilled amulet",
"chilled lavae",
"chiminea",
"clock",
"clockwork bishop",
"clockwork bishops",
"clockwork castle",
"clockwork knight",
"clockwork knights",
"clockwork monsters",
"clockwork rook",
"cloth",
"clothes",
"clothing",
"cobblestone",
"cobblestones",
"coconade",
"coconut",
"codex umbra",
"coffee",
"coffee beans",
"coffee plant",
"cold",
"compass",
"console",
"construction amulet",
"controls",
"cooked banana",
"cooked batilisk wing",
"cooked birchnut",
"cooked blue cap",
"cooked cactus flesh",
"cooked cave banana",
"cooked eel",
"cooked egg",
"cooked fish",
"cooked frog legs",
"cooked green cap",
"cooked leafy meat",
"cooked mandrake",
"cooked meat",
"cooked monster meat",
"cooked monster meat",
"cooked morsel",
"cooked morsel",
"cooked red cap",
"cooking",
"coral",
"coral reef",
"corn",
"corn seeds",
"corns",
"crabbit",
"crabbit den",
"craftable",
"craftable items",
"craftables",
"crafting",
"crank thing",
"crate",
"cratered moonrock",
"crawling horror",
"creatures",
"crimson feather",
"critters",
"critters tab",
"crock pot",
"crock pot",
"crock pot dishes",
"crock pot recipes",
"crock pot recipes",
"crop seeds",
"crop seeds",
"crops",
"crow",
"crow feather",
"crows",
"cursed",
"cut grass",
"cut reeds",
"cut stone",
"cutlass supreme",
"cyclum puzzles",
"dairy",
"damaged",
"damaged bishop",
"damaged knight",
"damaged rook",
"dangling depth dweller",
"dapper vest",
"dark petal",
"dark petals",
"dark sword",
"darkness",
"day",
"dead",
"dead jellyfish",
"dead wobsters",
"deadly feast",
"death",
"debris",
"debugspawn",
"deciduous forest",
"deciduous turf",
"deconstruction staff",
"deerclops",
"deerclops eyeball",
"depth dweller",
"depths worm",
"desert",
"dessicated tentacle",
"directional sign",
"disease",
"divining rod",
"dlc",
"dogfish",
"don't starve together",
"door",
"down feather",
"doydoy",
"doydoy egg",
"doydoy feather",
"doydoy nest",
"dragon fruit",
"dragon fruit seeds",
"dragon pie",
"dragonflies",
"dragonfly",
"dragonpie",
"dragoon",
"dragoon den",
"dragoon egg",
"dragoon heart",
"dress",
"dried jellyfish",
"dried seaweed",
"dripple pipes",
"drumstick",
"dry",
"drying rack",
"drying racks",
"dubloons",
"dumbrella",
"durability",
"durian",
"durian seeds",
"dusk",
"dying",
"earthquake",
"earthquakes",
"eel",
"egg",
"eggplant",
"eggplant seeds",
"eggs",
"electric dart",
"electric isosceles",
"electric milk",
"electrical doodad",
"elephant cactus",
"emotes",
"empty bottle",
"end table",
"endothermic fire",
"endothermic fire pit",
"equipable items",
"evergreen",
"evergreens",
"evil flower",
"evil flowers",
"ewecus",
"ewelet",
"experience",
"extra smelly durian",
"eye bone",
"eye plant",
"eyebrella",
"eyeplant",
"eyeshot",
"fake kazoo",
"farm",
"farm plot",
"farm plots",
"farming",
"farming the caves",
"farms",
"fashion melon",
"fat",
"feather",
"feather hat",
"feather pencil",
"feathers",
"features",
"fern",
"ferns",
"fertilizer",
"fertilizers",
"fight",
"fight tab",
"filler",
"fire",
"fire dart",
"fire hound",
"fire staff",
"fireflies",
"fish",
"fish morsel",
"fish tacos",
"fishbone",
"fishermerm",
"fishermerm's hut",
"fishes",
"fishing rod",
"fishsticks",
"fist full of jam",
"fleshy bulb",
"flint",
"floaty boaty knight",
"flooding",
"floor",
"floral shirt",
"florid postern",
"flotsam",
"flower",
"flower salad",
"flup",
"fog",
"food",
"food tab",
"football helmet",
"forest",
"forest turf",
"fossils",
"freezing",
"fresh fruit crepes",
"friendly scarecrow",
"frog",
"frog legs",
"froggle bunwich",
"fruit",
"fruit medley",
"funcap",
"fungal turf",
"fur tuft",
"garland",
"gears",
"gemology tab",
"gems",
"ghost",
"ghost characters",
"giant",
"giants",
"gigantic beehive",
"glommer",
"glommer's flower",
"glommer's goop",
"glommer's statue",
"glommer's wings",
"glossary",
"glow berry",
"gobbler",
"gold nugget",
"golden key",
"goose",
"goose egg",
"gramaphone",
"gramaphone parts",
"grass gekko",
"grass suit",
"grass tuft",
"grass turf",
"grasslands",
"grassy thing",
"grave",
"graveyard",
"green gem",
"green moonlens",
"grumble bee",
"guacamole",
"guano",
"guano turf",
"guardian",
"guardian's horn",
"gunpowder",
"gunpowder barrel",
"hail",
"hallowed nights",
"ham bat",
"hammer",
"harp statue",
"harpoon",
"hatching a smallbird",
"healing salve",
"health",
"hibearnation vest",
"hollow stump",
"honey",
"honey ham",
"honey nuggets",
"honey poultice",
"honeycomb",
"horn",
"horned helmet",
"hound",
"hound mound",
"hound repelling",
"hound's tooth",
"houndius shootius",
"howling conch",
"hunger",
"hurricane",
"hutch",
"ice",
"ice box",
"ice cream",
"ice cube",
"ice flingomatic",
"ice maker 3000",
"ice staff",
"importing",
"insulated pack",
"inventory",
"iridescent gem",
"iron key",
"it burns",
"items and monsters",
"jellybeans",
"jellyfish",
"jerky",
"juicy berries",
"juicy berry bush",
"jungle",
"jungle tree seed",
"jungle turf",
"kabobs",
"klei entertainment",
"koalefant",
"koalefant trunk",
"krampus",
"krissure",
"labyrinth",
"lantern",
"lava pit",
"lava pool",
"lavae",
"lavae egg",
"lavae tooth",
"leafy meat",
"lesser glow berry",
"lichen",
"life giving amulet",
"life jacket",
"light bulb",
"light flower",
"light tab",
"lightning",
"lightning rod",
"limestone",
"limestone suit",
"limpet rock",
"limpets",
"living log",
"lobster bisque",
"lobster dinner",
"log",
"log raft",
"log suit",
"long pig",
"lua",
"lucky hat",
"lucy the axe",
"lumpy",
"luxury fan",
"machete",
"mactusk",
"mactusk and son",
"magic seal",
"magic tab",
"magiluminescence",
"magma",
"magma field",
"magma pile",
"magma turf",
"malfunctioning novelty ride",
"mandrake",
"mandrake soup",
"mangrove",
"mangrove tree",
"manure",
"map",
"map scroll",
"marble",
"marble bean",
"marble pillar",
"marble sculptures",
"marble shrub",
"marble statues",
"marble suit",
"marble tree",
"marsh",
"marsh turf",
"maxwell",
"maxwell clothes",
"maxwell quotes",
"maxwell statue",
"maxwell's door",
"maxwell's head",
"maxwell's light",
"maxwell's mosquito trap",
"maxwell's tooth trap",
"maxwell's world",
"meadow",
"meadow turf",
"meat",
"meat effigy",
"meatballs",
"meatfarm",
"meats",
"meaty stew",
"melonsicle",
"merm",
"merm head",
"merm hut",
"message in a bottle",
"metal potato thing",
"meteor",
"mild",
"military",
"miner hat",
"mini glacier",
"mobs",
"mods",
"moggles",
"moleworm",
"monsoon",
"monster",
"monster food",
"monster jerky",
"monster lasagna",
"monster meat",
"monster tartare",
"moon caller's staff",
"moon cycle",
"moon rock",
"moon rock wall",
"moon stone",
"moondial",
"moonlens",
"morgue",
"morning star",
"morsel",
"mosaic",
"mosling",
"mosquito",
"mosquito sack",
"mud turf",
"mushroom lights",
"mushroom planter",
"mushroom spore",
"mushrooms",
"mushtree",
"mushtree forest",
"mussel",
"mussel bouillabaise",
"mussel stick",
"nautical tab",
"night armor",
"night light",
"nightmare amulet",
"nightmare cycle",
"nightmare fuel",
"nightmare fuel farming",
"nightmare light",
"nightmare lock",
"nightmare throne",
"nitre",
"nomadic survival",
"normal",
"note",
"npc",
"obelisk",
"obsidian",
"obsidian armor",
"obsidian axe",
"obsidian boulder",
"obsidian fire pit",
"obsidian machete",
"obsidian spear",
"obsidian workbench",
"ocean",
"octopus chest",
"ocuvigil",
"old bell",
"on tentacles",
"orange gem",
"orange moonlens",
"ornate chest",
"overheating",
"packim baggims",
"palm leaf",
"palm leaf hut",
"palm tree",
"palm treeguard",
"pan flute",
"panic room",
"papyrus",
"parrot pirate",
"particulate purifier",
"peg leg",
"pengull",
"petals",
"petrified tree",
"phlegm",
"physical damage absorption",
"pickaxe",
"picking your armor",
"pierogi",
"pig",
"pig head",
"pig house",
"pig king",
"pig skin",
"pig torch",
"pig village",
"pile of balloons",
"pillars",
"pine cone",
"pirate hat",
"piratihatitator",
"pitchfork",
"plants",
"poison",
"poison hole",
"poison mosquito",
"poison spear",
"poisonous hole",
"pomegranate",
"pond",
"portable crock pot",
"potted fern",
"potter's wheel",
"powdercake",
"prefab list",
"prestihatitator",
"pretty parasol",
"prime ape",
"prime ape hut",
"puffy vest",
"pumpkin",
"pumpkin cookies",
"pumpkin lantern",
"purple gem",
"purple moonlens",
"quacken",
"rabbit",
"rabbit earmuffs",
"rabbit hole",
"rabbit hutch",
"rabbit trap",
"radio",
"raft",
"rain",
"rain coat",
"rain hat",
"rainometer",
"ratatouille",
"raw fish",
"rawling",
"razor",
"red gem",
"red hound",
"red moonlens",
"reeds",
"refine",
"regrowth",
"regular jungle tree",
"relic",
"renewable farming",
"research points list",
"ring thing",
"road",
"road turf",
"rock den",
"rock lobster",
"rocks",
"rocky plains",
"rocky turf",
"rockyland",
"rope",
"rot",
"rotten egg",
"row boat",
"royal jelly",
"ruins",
"rundown house",
"runic turf",
"sacred",
"saddle",
"saddlehorn",
"sail",
"sail stick",
"salt lick",
"sand",
"sand castle",
"sandbag",
"sandbox",
"sandy pile",
"sandy turf",
"sanity",
"sapling",
"savanna",
"savanna turf",
"saving",
"scaled chest",
"scaled flooring",
"scaled furnace",
"scalemail",
"scales",
"science machine",
"science tab",
"screw thing",
"sculpt tab",
"sea hound",
"sea sack",
"sea trap",
"seafood gumbo",
"seagull",
"sealnado",
"seashell",
"seashell suit",
"season",
"seasons",
"seaweed",
"seaworthy",
"seeds",
"set piece",
"sewing kit",
"shadow atrium",
"shadow chester",
"shadow creature",
"shadow digger",
"shadow duelist",
"shadow logger",
"shadow manipulator",
"shadow miner",
"shadow pieces",
"shadow tentacles",
"shark fin",
"shark fin soup",
"shark gills",
"shark tooth crown",
"sharkitten",
"sharkitten den",
"shelmet",
"shipwrecked nomadic bases",
"shoal",
"shopkeeper",
"shovel",
"shroom skin",
"sign",
"silk",
"silly monkey ball",
"sinkhole",
"skeleton",
"sketch",
"skins",
"skull chest",
"sleek hat",
"sleeping",
"sleepytime stories",
"slimey turf",
"slipstor",
"slot machine",
"slurper",
"slurper pelt",
"slurtle",
"slurtle mound",
"slurtle slime",
"small jerky",
"smallbird",
"smallish",
"snake",
"snake oil",
"snakeskin",
"snakeskin hat",
"snakeskin jacket",
"snakeskin rug",
"snow",
"snow chester",
"snurtle shell armor",
"soundtrack",
"spear",
"spear gun",
"speargun",
"speculated characters",
"speculated items",
"spicy chili",
"spider",
"spider den",
"spider eggs",
"spider gland",
"spider queen",
"spiderhat",
"spiky",
"spiky bush",
"spilagmite",
"spitter",
"splumonkey",
"splumonkey pod",
"spoiled fish",
"sporecap",
"spring",
"spyglass",
"stagehand",
"stalagmite",
"stalagmite biomes",
"star caller's staff",
"steam trading card",
"steamer trunk",
"steel wool",
"sticky webbing",
"stinger",
"stink ray",
"story line",
"straw hat",
"strong winds",
"structures",
"structures tab",
"stuffed eggplant",
"summer",
"summer cave base",
"summer frest",
"sunk boat",
"sunken boat",
"sunken forest",
"surf and turf",
"surface world",
"surfboard",
"survival mode",
"survival tab",
"surviving in lights out",
"surviving shipwrecked",
"suspicious bubbles",
"suspicious marble",
"suspicious moonrock",
"sweet potato",
"sweet potato souffle",
"sweetener",
"swordfish",
"taffy",
"tail of three cats",
"tallbird",
"tallbird egg",
"tallbird nest",
"tam of shanter",
"tarnished crown",
"telelocator focus",
"telelocator staff",
"telltale heart",
"tent",
"tentacle",
"tentacle spike",
"tentacle spots",
"tesla tree",
"tex",
"the sea legs",
"the big picture",
"the end is nigh",
"the lazy explorer",
"the lazy forager",
"the lost fragment",
"the performance artist",
"the screecher",
"the strongman",
"thermal measurer",
"thermal stone",
"thick fur",
"things",
"thulecite",
"thulecite club",
"thulecite crown",
"thulecite fragments",
"thulecite medallion",
"thulecite suit",
"tidal marsh turf",
"tidal pool",
"tiger shark",
"toadstool",
"tools tab",
"tooth trap",
"top hat",
"torch",
"totally normal",
"toucan",
"touch stone",
"trail mix",
"trailer cyphers",
"trap",
"trawl net",
"tree",
"tree clump",
"treeguard",
"trident",
"trinkets",
"tropical fan",
"tropical fish",
"tropical parasol",
"tumbleweed",
"turbine blades",
"turfs",
"turkey dinner",
"twiggy tree",
"twiggy tree cone",
"twigs",
"umbrella",
"unagi",
"varg",
"vegetable",
"venom gland",
"village",
"vine",
"viney bush",
"volcanic tab",
"volcano",
"volcano altar of snackrifice",
"volcano staff",
"volcano turf",
"volt goat",
"volt goat horn",
"waffles",
"walani",
"walani clothes",
"walani quotes",
"walking cane",
"wall",
"walrus camp",
"walrus tusk",
"wardrobe",
"warly clothes",
"warly quotes",
"warrior",
"water balloon",
"water beefalo",
"watermelon",
"watery grave",
"waves",
"weapon",
"weather pain",
"webber",
"webber clothes",
"webber quotes",
"webber's skull",
"wee mactusk",
"wendy",
"wendy clothes",
"wendy quotes",
"werepig",
"wes",
"wes clothes",
"wes quotes",
"wet goop",
"wetness",
"whale",
"whirly fan",
"white whale",
"wickerbottom",
"wickerbottom clothes",
"wickerbottom quotes",
"wigfrid",
"wigfrid clothes",
"wigfrid quotes",
"wilbur clothes",
"wilbur quotes",
"wildbore",
"wildbore head",
"wildbore house",
"wilds",
"william carter puzzles",
"willow",
"willow clothes",
"willow quotes",
"willow's lighter",
"wilson",
"wilson clothes",
"wilson quotes",
"windbreaker",
"winter",
"winter hat",
"wobster",
"wobster den",
"wolfgang",
"wolfgang clothes",
"wolfgang quotes",
"wood fence",
"wood gate",
"wooden flooring",
"wooden potato thing",
"wooden thing",
"woodie",
"woodie clothes",
"woodie quotes",
"woodie's curse",
"woodlegs",
"woodlegs clothes",
"woodlegs quotes",
"woodlegs' keys",
"world",
"world customization",
"world generation",
"world vs caves",
"worm hole",
"wreck",
"x marks the spot",
"yaarctopus",
"yellow gem",
"yellow moonlens"]

var result = {};
all.forEach(function(item, idx) {
  if (!(item in result)) {
    result[item] = 0;
  }
})
  


console.log(result);