var webPage = require('webpage');
var fs = require('fs');
var page = webPage.create();
var url = 'http://dontstarve.wikia.com/index.php?title=Special%3AAllPages&from=&to=&namespace=14'
var path = 'output.txt';

// var evalGetThreads = function() {
//   var urlList = [];
//   $('.mw-allpages-table-chunk a').each(function(idx, item){
//     urlList.push(item.href);
//   });
//   return urlList;
// }

var urlList = ["http://dontstarve.wikia.com/wiki/Category:A_New_Reign",
"http://dontstarve.wikia.com/wiki/Category:Adminship_Requests",
"http://dontstarve.wikia.com/wiki/Category:Adminship_requests",
"http://dontstarve.wikia.com/wiki/Category:Adventure_Mode",
"http://dontstarve.wikia.com/wiki/Category:Always_Available",
"http://dontstarve.wikia.com/wiki/Category:Amulets",
"http://dontstarve.wikia.com/wiki/Category:Ancient_Tab",
"http://dontstarve.wikia.com/wiki/Category:Ancient_Tier_1",
"http://dontstarve.wikia.com/wiki/Category:Ancient_Tier_2",
"http://dontstarve.wikia.com/wiki/Category:Animals",
"http://dontstarve.wikia.com/wiki/Category:Apparel",
"http://dontstarve.wikia.com/wiki/Category:Aquatic_Mobs",
"http://dontstarve.wikia.com/wiki/Category:Area_of_Effect",
"http://dontstarve.wikia.com/wiki/Category:Armor",
"http://dontstarve.wikia.com/wiki/Category:Article_management_templates",
"http://dontstarve.wikia.com/wiki/Category:Article_stubs",
"http://dontstarve.wikia.com/wiki/Category:Articles_need_revision",
"http://dontstarve.wikia.com/wiki/Category:Articles_to_be_clarified",
"http://dontstarve.wikia.com/wiki/Category:Articles_to_be_deleted",
"http://dontstarve.wikia.com/wiki/Category:Articles_to_be_expanded",
"http://dontstarve.wikia.com/wiki/Category:Articles_to_be_merged",
"http://dontstarve.wikia.com/wiki/Category:Articles_to_be_verified",
"http://dontstarve.wikia.com/wiki/Category:Articles_using_improper_tone",
"http://dontstarve.wikia.com/wiki/Category:Articles_using_instructional_language",
"http://dontstarve.wikia.com/wiki/Category:Articles_using_second-person_pronouns",
"http://dontstarve.wikia.com/wiki/Category:Articles_with_missing_item_infobox_stack_value",
"http://dontstarve.wikia.com/wiki/Category:Beach",
"http://dontstarve.wikia.com/wiki/Category:Biomes",
"http://dontstarve.wikia.com/wiki/Category:Birds",
"http://dontstarve.wikia.com/wiki/Category:Blocked_users",
"http://dontstarve.wikia.com/wiki/Category:Blog_posts",
"http://dontstarve.wikia.com/wiki/Category:Blueprint_Exclusive",
"http://dontstarve.wikia.com/wiki/Category:Boats",
"http://dontstarve.wikia.com/wiki/Category:Books",
"http://dontstarve.wikia.com/wiki/Category:Books_Tab",
"http://dontstarve.wikia.com/wiki/Category:Boss_Dropped_Items",
"http://dontstarve.wikia.com/wiki/Category:Boss_Monsters",
"http://dontstarve.wikia.com/wiki/Category:Browse",
"http://dontstarve.wikia.com/wiki/Category:Bureaucrat_requests",
"http://dontstarve.wikia.com/wiki/Category:Cartography_Tab",
"http://dontstarve.wikia.com/wiki/Category:Category_templates",
"http://dontstarve.wikia.com/wiki/Category:Cave_Creatures",
"http://dontstarve.wikia.com/wiki/Category:Character-Specific",
"http://dontstarve.wikia.com/wiki/Category:Character_Clothes",
"http://dontstarve.wikia.com/wiki/Category:Character_Images",
"http://dontstarve.wikia.com/wiki/Category:Character_Quotes",
"http://dontstarve.wikia.com/wiki/Category:Characters",
"http://dontstarve.wikia.com/wiki/Category:Citation_templates",
"http://dontstarve.wikia.com/wiki/Category:Clarification_needed",
"http://dontstarve.wikia.com/wiki/Category:Clockwork_Monsters",
"http://dontstarve.wikia.com/wiki/Category:Community",
"http://dontstarve.wikia.com/wiki/Category:Containers",
"http://dontstarve.wikia.com/wiki/Category:Content",
"http://dontstarve.wikia.com/wiki/Category:Context-link_templates",
"http://dontstarve.wikia.com/wiki/Category:Cooling",
"http://dontstarve.wikia.com/wiki/Category:Craftable_Items",
"http://dontstarve.wikia.com/wiki/Category:Craftable_Structures",
"http://dontstarve.wikia.com/wiki/Category:Crafting_Stations",
"http://dontstarve.wikia.com/wiki/Category:Crafting_Tiers",
"http://dontstarve.wikia.com/wiki/Category:Crock_Pot_Recipes",
"http://dontstarve.wikia.com/wiki/Category:Crockpot_Recipies",
"http://dontstarve.wikia.com/wiki/Category:Custodian_requests",
"http://dontstarve.wikia.com/wiki/Category:Cycle",
"http://dontstarve.wikia.com/wiki/Category:DLC",
"http://dontstarve.wikia.com/wiki/Category:DLC_Images",
"http://dontstarve.wikia.com/wiki/Category:DST_Images",
"http://dontstarve.wikia.com/wiki/Category:Dairy",
"http://dontstarve.wikia.com/wiki/Category:Data_templates",
"http://dontstarve.wikia.com/wiki/Category:Dedicated_Servers",
"http://dontstarve.wikia.com/wiki/Category:Design_templates",
"http://dontstarve.wikia.com/wiki/Category:Diggable_Objects",
"http://dontstarve.wikia.com/wiki/Category:Disambiguations",
"http://dontstarve.wikia.com/wiki/Category:Diurnals",
"http://dontstarve.wikia.com/wiki/Category:Don%27t_Starve_Together",
"http://dontstarve.wikia.com/wiki/Category:Dress_Tab",
"http://dontstarve.wikia.com/wiki/Category:Earthshakers",
"http://dontstarve.wikia.com/wiki/Category:Edible_Items",
"http://dontstarve.wikia.com/wiki/Category:Eggs",
"http://dontstarve.wikia.com/wiki/Category:Equipable_Items",
"http://dontstarve.wikia.com/wiki/Category:Fairuse",
"http://dontstarve.wikia.com/wiki/Category:Fat",
"http://dontstarve.wikia.com/wiki/Category:Featured_Articles",
"http://dontstarve.wikia.com/wiki/Category:Featured_article_templates",
"http://dontstarve.wikia.com/wiki/Category:Featured_articles",
"http://dontstarve.wikia.com/wiki/Category:Fertilizer",
"http://dontstarve.wikia.com/wiki/Category:Fight_Tab",
"http://dontstarve.wikia.com/wiki/Category:Files",
"http://dontstarve.wikia.com/wiki/Category:Fire_Starter",
"http://dontstarve.wikia.com/wiki/Category:Fishes",
"http://dontstarve.wikia.com/wiki/Category:Flammable_Objects",
"http://dontstarve.wikia.com/wiki/Category:Flying_Creatures",
"http://dontstarve.wikia.com/wiki/Category:Followers",
"http://dontstarve.wikia.com/wiki/Category:Food",
"http://dontstarve.wikia.com/wiki/Category:Food_Tab",
"http://dontstarve.wikia.com/wiki/Category:Fruits",
"http://dontstarve.wikia.com/wiki/Category:Fuel",
"http://dontstarve.wikia.com/wiki/Category:Game_Tabs",
"http://dontstarve.wikia.com/wiki/Category:Gameplay",
"http://dontstarve.wikia.com/wiki/Category:Gemology_Tab",
"http://dontstarve.wikia.com/wiki/Category:Gems",
"http://dontstarve.wikia.com/wiki/Category:Guides",
"http://dontstarve.wikia.com/wiki/Category:Hats",
"http://dontstarve.wikia.com/wiki/Category:Healing",
"http://dontstarve.wikia.com/wiki/Category:Health_Loss",
"http://dontstarve.wikia.com/wiki/Category:Help",
"http://dontstarve.wikia.com/wiki/Category:Help_page_templates",
"http://dontstarve.wikia.com/wiki/Category:Hidden_categories",
"http://dontstarve.wikia.com/wiki/Category:Hiders",
"http://dontstarve.wikia.com/wiki/Category:Homepage_templates",
"http://dontstarve.wikia.com/wiki/Category:Hostile_Creatures",
"http://dontstarve.wikia.com/wiki/Category:Icons",
"http://dontstarve.wikia.com/wiki/Category:Image_wiki_templates",
"http://dontstarve.wikia.com/wiki/Category:Images",
"http://dontstarve.wikia.com/wiki/Category:Incomplete",
"http://dontstarve.wikia.com/wiki/Category:Incorrect_Infobox_Used",
"http://dontstarve.wikia.com/wiki/Category:Indestructible_Object",
"http://dontstarve.wikia.com/wiki/Category:Infobox_missing_crafting_desription",
"http://dontstarve.wikia.com/wiki/Category:Infobox_missing_spawncodes",
"http://dontstarve.wikia.com/wiki/Category:Infobox_templates",
"http://dontstarve.wikia.com/wiki/Category:Infoicon_templates",
"http://dontstarve.wikia.com/wiki/Category:Innocents",
"http://dontstarve.wikia.com/wiki/Category:Interface",
"http://dontstarve.wikia.com/wiki/Category:Item_Images",
"http://dontstarve.wikia.com/wiki/Category:Items",
"http://dontstarve.wikia.com/wiki/Category:License_templates",
"http://dontstarve.wikia.com/wiki/Category:Light_Sources",
"http://dontstarve.wikia.com/wiki/Category:Light_Tab",
"http://dontstarve.wikia.com/wiki/Category:Limited_use",
"http://dontstarve.wikia.com/wiki/Category:Lore",
"http://dontstarve.wikia.com/wiki/Category:Low-quality_images",
"http://dontstarve.wikia.com/wiki/Category:Magic",
"http://dontstarve.wikia.com/wiki/Category:Magic_Tab",
"http://dontstarve.wikia.com/wiki/Category:Magic_Tier_1",
"http://dontstarve.wikia.com/wiki/Category:Magic_Tier_2",
"http://dontstarve.wikia.com/wiki/Category:Meats",
"http://dontstarve.wikia.com/wiki/Category:Media_templates",
"http://dontstarve.wikia.com/wiki/Category:Melee_Weapons",
"http://dontstarve.wikia.com/wiki/Category:Menu",
"http://dontstarve.wikia.com/wiki/Category:Merchandising_Images",
"http://dontstarve.wikia.com/wiki/Category:Mineable_Objects",
"http://dontstarve.wikia.com/wiki/Category:Minerals",
"http://dontstarve.wikia.com/wiki/Category:Missing_multi-quotes",
"http://dontstarve.wikia.com/wiki/Category:Mob_Dropped_Items",
"http://dontstarve.wikia.com/wiki/Category:Mob_Housing",
"http://dontstarve.wikia.com/wiki/Category:Mob_Images",
"http://dontstarve.wikia.com/wiki/Category:Mob_Spawning_Entities",
"http://dontstarve.wikia.com/wiki/Category:Mobs",
"http://dontstarve.wikia.com/wiki/Category:Mods",
"http://dontstarve.wikia.com/wiki/Category:Monster_Foods",
"http://dontstarve.wikia.com/wiki/Category:Monsters",
"http://dontstarve.wikia.com/wiki/Category:Multipage_articles",
"http://dontstarve.wikia.com/wiki/Category:Naturally_Spawning_Objects",
"http://dontstarve.wikia.com/wiki/Category:Nautical_Tab",
"http://dontstarve.wikia.com/wiki/Category:Navbox_templates",
"http://dontstarve.wikia.com/wiki/Category:Navigation_templates",
"http://dontstarve.wikia.com/wiki/Category:Neutral_Creatures",
"http://dontstarve.wikia.com/wiki/Category:Never_archived_blogs",
"http://dontstarve.wikia.com/wiki/Category:New_pages",
"http://dontstarve.wikia.com/wiki/Category:Nightmare_State_Indicator",
"http://dontstarve.wikia.com/wiki/Category:Nocturnals",
"http://dontstarve.wikia.com/wiki/Category:Non-Flammable",
"http://dontstarve.wikia.com/wiki/Category:Non-Renewable",
"http://dontstarve.wikia.com/wiki/Category:Notice_templates",
"http://dontstarve.wikia.com/wiki/Category:Object_Destroyers",
"http://dontstarve.wikia.com/wiki/Category:Object_Images",
"http://dontstarve.wikia.com/wiki/Category:Ocean",
"http://dontstarve.wikia.com/wiki/Category:Old_forum_templates",
"http://dontstarve.wikia.com/wiki/Category:Organisation",
"http://dontstarve.wikia.com/wiki/Category:Organization",
"http://dontstarve.wikia.com/wiki/Category:Pages_with_broken_file_links",
"http://dontstarve.wikia.com/wiki/Category:ParserFunctions",
"http://dontstarve.wikia.com/wiki/Category:Passive_Creatures",
"http://dontstarve.wikia.com/wiki/Category:Periodic_Threat",
"http://dontstarve.wikia.com/wiki/Category:Perishables",
"http://dontstarve.wikia.com/wiki/Category:Plants",
"http://dontstarve.wikia.com/wiki/Category:Portal",
"http://dontstarve.wikia.com/wiki/Category:Programming",
"http://dontstarve.wikia.com/wiki/Category:Quote_templates",
"http://dontstarve.wikia.com/wiki/Category:Ranged_Creatures",
"http://dontstarve.wikia.com/wiki/Category:Ranged_Weapons",
"http://dontstarve.wikia.com/wiki/Category:Rare_Blueprint_Exclusive",
"http://dontstarve.wikia.com/wiki/Category:Redirect",
"http://dontstarve.wikia.com/wiki/Category:Refine_Tab",
"http://dontstarve.wikia.com/wiki/Category:Reign_of_Giants",
"http://dontstarve.wikia.com/wiki/Category:Removed_Features",
"http://dontstarve.wikia.com/wiki/Category:Resources",
"http://dontstarve.wikia.com/wiki/Category:Resurrection",
"http://dontstarve.wikia.com/wiki/Category:Rollback_Requests",
"http://dontstarve.wikia.com/wiki/Category:Rollback_requests",
"http://dontstarve.wikia.com/wiki/Category:Ruins_Creatures",
"http://dontstarve.wikia.com/wiki/Category:Sanity_Boost",
"http://dontstarve.wikia.com/wiki/Category:Sanity_Loss",
"http://dontstarve.wikia.com/wiki/Category:Science",
"http://dontstarve.wikia.com/wiki/Category:Science_Tab",
"http://dontstarve.wikia.com/wiki/Category:Science_Tier_1",
"http://dontstarve.wikia.com/wiki/Category:Science_Tier_2",
"http://dontstarve.wikia.com/wiki/Category:Scrollbox_templates",
"http://dontstarve.wikia.com/wiki/Category:Seasons",
"http://dontstarve.wikia.com/wiki/Category:Shadow_Tab",
"http://dontstarve.wikia.com/wiki/Category:Shipwrecked",
"http://dontstarve.wikia.com/wiki/Category:Site_administration_templates",
"http://dontstarve.wikia.com/wiki/Category:Site_maintenance",
"http://dontstarve.wikia.com/wiki/Category:Site_policy_pages",
"http://dontstarve.wikia.com/wiki/Category:Speed_Boost",
"http://dontstarve.wikia.com/wiki/Category:Speed_Loss",
"http://dontstarve.wikia.com/wiki/Category:Spiders",
"http://dontstarve.wikia.com/wiki/Category:Staves",
"http://dontstarve.wikia.com/wiki/Category:Structures",
"http://dontstarve.wikia.com/wiki/Category:Structures_Tab",
"http://dontstarve.wikia.com/wiki/Category:Summer",
"http://dontstarve.wikia.com/wiki/Category:Supplemental_Material",
"http://dontstarve.wikia.com/wiki/Category:Supplemental_material",
"http://dontstarve.wikia.com/wiki/Category:Surface_Creatures",
"http://dontstarve.wikia.com/wiki/Category:Survival_Tab",
"http://dontstarve.wikia.com/wiki/Category:Sweeteners",
"http://dontstarve.wikia.com/wiki/Category:Template_documentation",
"http://dontstarve.wikia.com/wiki/Category:Templates",
"http://dontstarve.wikia.com/wiki/Category:Templates_without_documentation",
"http://dontstarve.wikia.com/wiki/Category:Things",
"http://dontstarve.wikia.com/wiki/Category:Tools_Tab",
"http://dontstarve.wikia.com/wiki/Category:Traps",
"http://dontstarve.wikia.com/wiki/Category:Trees",
"http://dontstarve.wikia.com/wiki/Category:Turf_Items",
"http://dontstarve.wikia.com/wiki/Category:Unstealable_Object",
"http://dontstarve.wikia.com/wiki/Category:Upcoming_Features",
"http://dontstarve.wikia.com/wiki/Category:User_Images",
"http://dontstarve.wikia.com/wiki/Category:User_page_templates",
"http://dontstarve.wikia.com/wiki/Category:Vegetables",
"http://dontstarve.wikia.com/wiki/Category:Venomous",
"http://dontstarve.wikia.com/wiki/Category:Videos",
"http://dontstarve.wikia.com/wiki/Category:Volcanic_Tab",
"http://dontstarve.wikia.com/wiki/Category:Volcanic_Tier",
"http://dontstarve.wikia.com/wiki/Category:Walls",
"http://dontstarve.wikia.com/wiki/Category:Warmth",
"http://dontstarve.wikia.com/wiki/Category:Water_Resistant",
"http://dontstarve.wikia.com/wiki/Category:Weapons",
"http://dontstarve.wikia.com/wiki/Category:Weather",
"http://dontstarve.wikia.com/wiki/Category:Winter",
"http://dontstarve.wikia.com/wiki/Category:World"];

var evalGetNames = function() {
  var list = [];
  try {
    var results = $('#mw-pages a');
    for (var i=0; i<results.length; i++) {
      list.push(results[i].title);
    }
  } catch (e) {
    list.push('error: ' + e)
  }
  return list;
}


function scrape(url, evaluate) {
  return page.open(url, function(status) {
    var data = page.evaluate(evaluate);
    console.log('writing...', url);
    fs.write(path, data, 'a');
    fs.write(path, ',\n', 'a');
    // phantom.exit(data);
  });
}

// urlList.forEach(function(idx, item) {
//   console.log('on: ', idx, item);
//   scrape(urlList[idx], evalGetNames);
// });

var current = 0;
setInterval(function() {
  if(current < urlList.length) {
    console.log(((urlList.length - current)*4)/60,' ---------on: ' + current + '/' + urlList.length, urlList[current]);
    scrape(urlList[current], evalGetNames);
    current += 1;
  }
}, 4000)